### ISSUE TITLE
cumulative function on ou x im dataset

### ISSUE THREAD

**Issue by wvp3** [achafetz/PartnerProgress#13]
cumulative(df,2018,2) function crashes out with error:

>   Error: `by` can't contain join column `operatingunit`, `countryname`, `psnu`, `psnuuid`, `snuprioritization`, ... which is missing from LHS 

for the ou x im dataset

This may be a capitalization / case issue - unsure if ignore.case=TRUE is possible for dplyr::full_join

**Comment by achafetz** [comment]
a couple issues:
1. case - I treat deal with everything in lower case (as opposed to the snake case as a default in the MSD), so it that's mostly what is going on here since the join is against lower case variables. 
https://github.com/achafetz/PartnerProgress/blob/7ae8c5849877911f6d90dad0fb3cb0f67f6f9cf8/R/cumulative.R#L49-L51

2. variable types - another issue that could trip up this code is that it assumes all the variables are either numeric or character. MSD has a high potential to import variables as logical, so that could be problematic for the meta data identification prior to the reshape 
https://github.com/achafetz/PartnerProgress/blob/7ae8c5849877911f6d90dad0fb3cb0f67f6f9cf8/R/cumulative.R#L31-L34

I'll see what I can do to incorporate both issues into a more generalizable function for the [ICPI Utilities package](https://github.com/ICPI/ICPIutilities).

**Comment by achafetz** [comment]
@wvp3, updated the ICPI Utilities package (v1.0.3) which should now allow you to create a cumulative variable/column for any MSD dataset via `add_cumulative()` regardless of case (and resolves the issue of logicals.

```
# ADD CUMULATIVE VARIABLE TO MSD ------------------------------------------------------------

#update/install package
    devtools::install_github("ICPI/ICPIutilities")

#import dataset
    df_mer <- readr::read_rds("~/Data/ICPI_MER_Structured_Dataset_OU_IM_FY17-18_20180515_v1_1.Rds")

#add cumulative column to dataset
    df_mer <- ICPIutilities::add_cumulative(df_mer)
```

**Comment by wvp3** [comment]
Just tried this on the ou x IM dataset, and it now appears to work correctly.  Thanks.
